lib/jirello_web/router.ex
defmodule JirelloWeb.Router do
  use JirelloWeb, :router

  import JirelloWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {JirelloWeb.LayoutView, :root}
    plug :protect_from_forgery

    plug :put_secure_browser_headers, %{
      "content-security-policy" =>
        "default-src 'self' 'unsafe-eval' 'unsafe-inline' http://unpkg.com https://cdn.jsdelivr.net; img-src 'self' data: https://ghchart.rshah.org www.gravatar.com"
    }

    plug :fetch_current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  # Set the layout for when a user registers or signs in
  pipeline :session_layout do
    plug :put_root_layout, {JirelloWeb.LayoutView, :session}
  end

  scope "/", JirelloWeb do
    pipe_through :browser

    get "/", PageController, :index
    get "/open", StatsController, :index
  end

  # Protected routes

  scope "/app", JirelloWeb do
    pipe_through [:browser, :session_layout, :require_authenticated_user]

    live "/", TasksLive
    resources "/projects", ProjectController
  end

  # Other scopes may use custom stacks.
  # scope "/api", JirelloWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: JirelloWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end

  ## Authentication routes

  scope "/", JirelloWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/log_in", UserSessionController, :new
    post "/users/log_in", UserSessionController, :create
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", JirelloWeb do
    pipe_through [:browser, :session_layout, :require_authenticated_user]

    get "/users/settings", UserSettingsController, :edit
    put "/users/settings", UserSettingsController, :update
    delete "/users/settings/:session_id", UserSettingsController, :delete
    get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email
  end

  scope "/", JirelloWeb do
    pipe_through [:browser]

    delete "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :edit
    post "/users/confirm/:token", UserConfirmationController, :update
  end
end

lib/jirello_web/views/shared_view.ex
defmodule JirelloWeb.SharedView do
  use JirelloWeb, :view
end

lib/jirello_web/templates/shared/_footer.html.heex
<footer class="bg-white" aria-labelledby="footer-heading">
  <h2 id="footer-heading" class="sr-only">Footer</h2>
  <div class="max-w-7xl mx-auto py-12 px-4 sm:px-6 lg:py-16 lg:px-8">
    <div class="xl:grid xl:grid-cols-3 xl:gap-8">
      <div class="space-y-8 xl:col-span-1">
        <span>
          <span class="sr-only">Jirello</span>
          <svg class="h-10 text-primary-600" viewBox="0 0 100 100" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
            <path d="M100 50C100 63.2608 94.7322 75.9785 85.3553 85.3553C75.9785 94.7322 63.2608 100 50 100C36.7392 100 24.0215 94.7322 14.6447 85.3553C5.26785 75.9785 2.00233e-06 63.2608 0 50L25 50C25 56.6304 27.6339 62.9893 32.3223 67.6777C37.0107 72.3661 43.3696 75 50 75C56.6304 75 62.9893 72.3661 67.6777 67.6777C72.3661 62.9893 75 56.6304 75 50H100Z"></path>
            <path d="M75 12.5C75 5.59644 80.5964 0 87.5 0V0C94.4036 0 100 5.59644 100 12.5V50H75V12.5Z"></path>
            <path d="M0 47.5C0 40.5964 5.59644 35 12.5 35V35C19.4036 35 25 40.5964 25 47.5V50H0V47.5Z"></path>
            <circle cx="50" cy="50" r="15"></circle>
          </svg>
        </span>

        <p class="text-gray-500 text-base">Built with ❤ by <a class="text-gray-400 hover:text-gray-500" href="https://twitter.com/ThatAlexCazacu">@ThatAlexCazacu</a></p>
        <div class="flex space-x-6">
          <a href="https://twitter.com/JirelloHQ" class="text-gray-400 hover:text-gray-500">
            <span class="sr-only">Twitter</span>
            <svg class="h-6 w-6" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true">
              <path
                d="M8.29 20.251c7.547 0 11.675-6.253 11.675-11.675 0-.178 0-.355-.012-.53A8.348 8.348 0 0022 5.92a8.19 8.19 0 01-2.357.646 4.118 4.118 0 001.804-2.27 8.224 8.224 0 01-2.605.996 4.107 4.107 0 00-6.993 3.743 11.65 11.65 0 01-8.457-4.287 4.106 4.106 0 001.27 5.477A4.072 4.072 0 012.8 9.713v.052a4.105 4.105 0 003.292 4.022 4.095 4.095 0 01-1.853.07 4.108 4.108 0 003.834 2.85A8.233 8.233 0 012 18.407a11.616 11.616 0 006.29 1.84" />
            </svg>
          </a>

          <a href="https://github.com/alexandru-cazacu/jirello" class="text-gray-400 hover:text-gray-500">
            <span class="sr-only">GitHub</span>
            <svg class="h-6 w-6" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true">
              <path fill-rule="evenodd"
                d="M12 2C6.477 2 2 6.484 2 12.017c0 4.425 2.865 8.18 6.839 9.504.5.092.682-.217.682-.483 0-.237-.008-.868-.013-1.703-2.782.605-3.369-1.343-3.369-1.343-.454-1.158-1.11-1.466-1.11-1.466-.908-.62.069-.608.069-.608 1.003.07 1.531 1.032 1.531 1.032.892 1.53 2.341 1.088 2.91.832.092-.647.35-1.088.636-1.338-2.22-.253-4.555-1.113-4.555-4.951 0-1.093.39-1.988 1.029-2.688-.103-.253-.446-1.272.098-2.65 0 0 .84-.27 2.75 1.026A9.564 9.564 0 0112 6.844c.85.004 1.705.115 2.504.337 1.909-1.296 2.747-1.027 2.747-1.027.546 1.379.202 2.398.1 2.651.64.7 1.028 1.595 1.028 2.688 0 3.848-2.339 4.695-4.566 4.943.359.309.678.92.678 1.855 0 1.338-.012 2.419-.012 2.747 0 .268.18.58.688.482A10.019 10.019 0 0022 12.017C22 6.484 17.522 2 12 2z"
                clip-rule="evenodd" />
            </svg>
          </a>
        </div>
      </div>
      <div class="mt-12 grid grid-cols-2 gap-8 xl:mt-0 xl:col-span-2">
        <div class="md:grid md:grid-cols-2 md:gap-8">
          <div class="mt-12 md:mt-0">
            <h3 class="text-sm font-semibold text-gray-400 tracking-wider uppercase">Support</h3>
            <ul role="list" class="mt-4 space-y-4">
              <%# <li><a href="/docs" class="text-base text-gray-500 hover:text-gray-900"> Documentation </a></li> %>
              <%# <li><a href="/status" class="text-base text-gray-500 hover:text-gray-900"> Status </a></li> %>
            </ul>
          </div>
          <div>
            <h3 class="text-sm font-semibold text-gray-400 tracking-wider uppercase">Community</h3>
            <ul role="list" class="mt-4 space-y-4">
              <li><a href="https://github.com/alexandru-cazacu/jirello" class="text-base text-gray-500 hover:text-gray-900"> GitHub </a></li>
              <li><a href="https://twitter.com/JirelloHQ" class="text-base text-gray-500 hover:text-gray-900"> Twitter </a></li>
              <li><a href="https://github.com/alexandru-cazacu/jirello/discussions" class="text-base text-gray-500 hover:text-gray-900"> Forum </a></li>
            </ul>
          </div>
        </div>
        <div class="md:grid md:grid-cols-2 md:gap-8">
          <div>
            <h3 class="text-sm font-semibold text-gray-400 tracking-wider uppercase">Company</h3>
            <ul role="list" class="mt-4 space-y-4">
              <%# <li><a href="/about" class="text-base text-gray-500 hover:text-gray-900"> About </a></li> %>
              <%# <li><a href="/blog" class="text-base text-gray-500 hover:text-gray-900"> Blog </a></li> %>
              <%= link "Metrics", to: Routes.stats_path(@conn, :index), class: "text-base text-gray-500 hover:text-gray-900" %>
            </ul>
          </div>
          <div class="mt-12 md:mt-0">
            <h3 class="text-sm font-semibold text-gray-400 tracking-wider uppercase">Legal</h3>
            <ul role="list" class="mt-4 space-y-4">
              <%# <li><a href="/privacy" class="text-base text-gray-500 hover:text-gray-900"> Privacy </a></li> %>
              <%# <li><a href="/terms" class="text-base text-gray-500 hover:text-gray-900"> Terms </a></li> %>
            </ul>
          </div>
        </div>
      </div>
    </div>
    <div class="mt-12 border-t border-gray-200 pt-8">
      <p class="text-base text-gray-400 xl:text-center">&copy; 2022 Jirello. All rights reserved.</p>
    </div>
  </div>
</footer>