lib/jirello_web/router.ex
defmodule JirelloWeb.Router do
  use JirelloWeb, :router

  import JirelloWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {JirelloWeb.LayoutView, :root}
    plug :protect_from_forgery

    plug :put_secure_browser_headers, %{
      "content-security-policy" =>
        "default-src 'self' 'unsafe-eval' 'unsafe-inline' http://unpkg.com https://cdn.jsdelivr.net; img-src 'self' data: https://ghchart.rshah.org www.gravatar.com"
    }

    plug :fetch_current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  # Set the layout for when a user registers or signs in
  pipeline :session_layout do
    plug :put_root_layout, {JirelloWeb.LayoutView, :session}
  end

  scope "/", JirelloWeb do
    pipe_through :browser

    get "/", PageController, :index
    get "/open", StatsController, :index
  end

  # Protected routes

  scope "/app", JirelloWeb do
    pipe_through [:browser, :session_layout, :require_authenticated_user]

    live "/", TasksLive
    resources "/projects", ProjectController
  end

  # Other scopes may use custom stacks.
  # scope "/api", JirelloWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: JirelloWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end

  ## Authentication routes

  scope "/", JirelloWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/log_in", UserSessionController, :new
    post "/users/log_in", UserSessionController, :create
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", JirelloWeb do
    pipe_through [:browser, :session_layout, :require_authenticated_user]

    get "/users/settings", UserSettingsController, :edit
    put "/users/settings", UserSettingsController, :update
    delete "/users/settings/:session_id", UserSettingsController, :delete
    get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email
  end

  scope "/", JirelloWeb do
    pipe_through [:browser]

    delete "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :edit
    post "/users/confirm/:token", UserConfirmationController, :update
  end
end

lib/jirello_web/controllers/user_session_controller.ex
defmodule JirelloWeb.UserSessionController do
  use JirelloWeb, :controller

  alias Jirello.Accounts
  alias JirelloWeb.UserAuth

  def new(conn, _params) do
    render(conn, "new.html", error_message: nil)
  end

  def create(conn, %{"user" => user_params}) do
    %{"email" => email, "password" => password} = user_params

    if user = Accounts.get_user_by_email_and_password(email, password) do
      UserAuth.log_in_user(conn, user, user_params)
    else
      # In order to prevent user enumeration attacks, don't disclose whether the email is registered.
      render(conn, "new.html", error_message: "Invalid email or password")
    end
  end

  def delete(conn, _params) do
    conn
    |> put_flash(:info, "Logged out successfully.")
    |> UserAuth.log_out_user()
  end
end

lib/jirello_web/views/user_session_view.ex
defmodule JirelloWeb.UserSessionView do
  use JirelloWeb, :view
  alias JirelloWeb.Live.Components.AlertComponent
end

lib/jirello_web/templates/user_session/new.html.heex
<%= if @error_message do %>
  <AlertComponent.error message={@error_message} />
<% end %>



<div class="min-h-full flex flex-col justify-center py-12 sm:px-6 lg:px-8">
  <div class="sm:mx-auto sm:w-full sm:max-w-md">
    <svg class="mx-auto h-12 w-auto text-primary-600"  xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" fill="currentColor" aria-hidden="true">
      <path d="M100 50C100 63.2608 94.7322 75.9785 85.3553 85.3553C75.9785 94.7322 63.2608 100 50 100C36.7392 100 24.0215 94.7322 14.6447 85.3553C5.26785 75.9785 2.00233e-06 63.2608 0 50L25 50C25 56.6304 27.6339 62.9893 32.3223 67.6777C37.0107 72.3661 43.3696 75 50 75C56.6304 75 62.9893 72.3661 67.6777 67.6777C72.3661 62.9893 75 56.6304 75 50H100Z"/>
      <path d="M75 12.5C75 5.59644 80.5964 0 87.5 0V0C94.4036 0 100 5.59644 100 12.5V50H75V12.5Z"/>
      <path d="M0 47.5C0 40.5964 5.59644 35 12.5 35V35C19.4036 35 25 40.5964 25 47.5V50H0V47.5Z"/>
      <circle cx="50" cy="50" r="15"/>
    </svg>
    <h2 class="mt-6 text-center text-3xl font-extrabold text-gray-900">Log In</h2>
  </div>

  <div class="mt-8 sm:mx-auto sm:w-full sm:max-w-md">
    <div class="bg-white py-8 px-4 shadow sm:rounded-lg sm:px-10">
      <.form let={f} for={@conn} action={Routes.user_session_path(@conn, :create)} as={:user} class="space-y-6">
        <div>
          <%= label f, :email, class: "block text-sm font-medium text-gray-700" %>
          <div class="mt-1 relative rounded-md shadow-sm">
            <div class="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
              <!-- Heroicon name: solid/mail -->
              <svg class="h-5 w-5 text-gray-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                <path d="M2.003 5.884L10 9.882l7.997-3.998A2 2 0 0016 4H4a2 2 0 00-1.997 1.884z" />
                <path d="M18 8.118l-8 4-8-4V14a2 2 0 002 2h12a2 2 0 002-2V8.118z" />
              </svg>
            </div>
            <%= email_input f, :email,
              autocomplete: "email",
              placeholder: "you@company.com",
              required: true,
              class: "focus:ring-primary-500 focus:border-primary-500 block w-full pl-10 sm:text-sm border-gray-300 rounded-md" %>
          </div>
          <%= error_tag f, :email %>
        </div>

        <div>
          <%= label f, :password, class: "block text-sm font-medium text-gray-700" %>
          <div class="mt-1 relative rounded-md shadow-sm">
            <div class="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
              <!-- Heroicon name: solid/lock-closed -->
              <svg class="h-5 w-5 text-gray-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                <path fill-rule="evenodd" d="M5 9V7a5 5 0 0110 0v2a2 2 0 012 2v5a2 2 0 01-2 2H5a2 2 0 01-2-2v-5a2 2 0 012-2zm8-2v2H7V7a3 3 0 016 0z" clip-rule="evenodd" />
              </svg>
            </div>
              <%= password_input f, :password,
                autocomplete: "current-password",
                placeholder: "••••••••••••",
                required: true,
                class: "focus:ring-primary-500 focus:border-primary-500 block w-full pl-10 sm:text-sm border-gray-300 rounded-md" %>
          </div>
          <%= error_tag f, :password %>
        </div>

        <div class="flex items-center justify-between">
          <div class="flex items-center">
            <%= checkbox f, :remember_me, class: "h-4 w-4 text-primary-600 focus:ring-primary-500 border-gray-300 rounded" %>
            <%= label f, :remember_me, "Remember me", class: "ml-2 block text-sm text-gray-900" %>
          </div>

          <div class="text-sm">
            <%= link "Forgot your password?", to: Routes.user_reset_password_path(@conn, :new), class: "font-medium text-primary-600 hover:text-primary-500" %>
          </div>
        </div>

        <%= submit "Log In", class: "w-full flex justify-center py-2 px-4 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-primary-600 hover:bg-primary-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-primary-500" %>
      </.form>
    </div>

    <p class="mt-6 text-center text-sm text-gray-600">
      Don't have an account?
      <%= link "Register", to: Routes.user_registration_path(@conn, :new), class: "font-medium text-primary-600 hover:text-primary-500" %>
    </p>
  </div>
</div>